[theme]
base = "light"
primaryColor = "#FFB6B9"                # Soft coral pink
backgroundColor = "#FFF0F5"             # Lavender blush
secondaryBackgroundColor = "#F8F9FA"    # Off-white containers
textColor = "#3D3D3D"                   # Dark muted gray
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"


